#!/bin/bash
export JAVA_PROGRAM_ARGS=`echo "$@"`
FILE_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

ENV_FILE="$FILE_PATH/rsq-browser.env"
if [[ "$RSQB_ENV_FILE" ]]; then
  ENV_FILE="$RSQB_ENV_FILE"
fi

if [ -f "$ENV_FILE" ]; then
    source "$ENV_FILE"
    echo "File '$ENV_FILE' exists and has been sourced."
fi

JAVA_ARGS="-Xmx10G"
if [[ "$RSQB_JAVA_ARGS" ]]; then
  JAVA_ARGS="$RSQB_JAVA_ARGS"
fi

JAVA_CMD="java"
if [[ "$RSQB_JAVA_CMD" ]]; then
  JAVA_CMD="$RSQB_JAVA_CMD"
fi

exec ${JAVA_CMD} ${JAVA_ARGS} -jar "$FILE_PATH/rsq-browser.jar" $JAVA_PROGRAM_ARGS