name: rsq-browser
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r=4.3
  - r-rmarkdown=2.29
  - r-ggplot2=3.5.1
  - r-htmltools=0.5.8.1
  - r-dplyr=1.1.4
  - r-dt=0.33
  - r-tidyr=1.3.1
  - r-plotly=4.10.4
  - r-r.utils=2.12.3
  - r-data.table=1.15.4
  - pandoc=2.19.2
  - cairo=1.16.0
  - xorg-libxt=1.2.1
  - fonts-anaconda=1
  - bioconductor-rsamtools=2.18.0