name: rsq-browser
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r=4.1.0
  - r-rmarkdown=2.16
  - r-ggplot2=3.3.6
  - r-htmltools=0.5.3
  - r-dplyr=1.1.0
  - r-dt=0.24
  - r-tidyr=1.2.1
  - r-rmdformats=1.0.4
  - r-plotly=4.10.2
  - r-r.utils=2.12.2
  - pandoc=2.19.2
  - cairo=1.16.0
  - xorg-libxt=1.2.1
  - fonts-anaconda=1
  - bioconductor-rsamtools=2.10.0