name: Create Release

on:
  push:
    tags:
    - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9

      - name: Build
        run: mvn install

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "target/rsq-browser-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
